{
    'name': 'Estate',
    'version': '1.0',
    'category': 'Real Estate',
    'summary': 'Real Estate Management System',
    'depends': ['base'],
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'views/estate_property_offer_views.xml',
        'views/estate_property_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/res_users_views.xml',
        'views/res_partner_views.xml',
        'views/estate_room_views.xml',
        'views/estate_room_type_views.xml',
        'views/estate_intervention_views.xml',
        'views/estate_rental_views.xml',
        'views/estate_menus.xml',
    ],
    'installable': True,
    'license': 'LGPL-3',
}
