from . import estate_property_type
from . import estate_property_tag
from . import estate_property
from . import estate_property_offer
from . import res_users_inherit
from . import estate_room_type
from . import estate_room
from . import estate_intervention
from . import estate_rental
from . import res_partner
